### ISSUE TITLE
1.6.0 in Helm Repository

### ISSUE THREAD

**Issue by pieterv-icloud-com** [LucasRoesler/openfaas-loki#23]
Hi, it does not appear that the 1.6.0 release is in the helm repository at  https://lucasroesler.com/openfaas-loki

**Comment by LucasRoesler** [comment]
I don't know why, but I was not getting notifications on this repo. I made several updates today, including publishing the Helm chart to GHCR, the new instructions are 

```sh
helm upgrade --install ofloki oci:://ghcr.io/lucasroesler/charts/openfaas-loki \
       --namespace openfaas \
       --set lokiURL=http://loki.monitoring:3100 \
       --set logLevel=DEBUG
```
