### ISSUE TITLE
I get a 404 error when I try to use the helm chart

### ISSUE THREAD

**Issue by mikeyGlitz** [LucasRoesler/openfaas-loki#32]
I receive an error 404 when trying to use the helm chart:
![image](https://user-images.githubusercontent.com/606924/168184168-85904a31-6b06-4de7-b65d-dfd288335cf5.png)

![image](https://user-images.githubusercontent.com/606924/168184203-c255ead1-1b13-4006-a7ba-ba21d162b440.png)

**Comment by alexellis** [comment]
@LucasRoesler are you still maintaining this project?

**Comment by LucasRoesler** [comment]
This slipped through my notifications, I will take a look

**Comment by blaisep** [comment]
FWIW, I ran into CrashLoop after running `arkade install openfaas-loki`
Arkade Version: 0.10.7
Git Commit: fec33ae658a975b59aa645f23d48e74930f43dda

**Comment by LucasRoesler** [comment]
Oh wow ... I fixed this but never pushed it :facepalm: 

```sh
$ ~/code/openfaas-loki (main↑1|✔)❯ git log
commit e5aeb8c (HEAD -> main)
Author: Lucas Roesler <roesler.lucas@gmail.com>
Date:   Tue Mar 8 16:19:16 2022 +0100

    docs: Update repo add instructions
    
    Update the URL for the helm-charts repo
    
    Signed-off-by: Lucas Roesler <roesler.lucas@gmail.com>

```

I just pushed this and the instructions show be updated now 

```sh
   helm repo add lucas http://lucasroesler.com/helm-charts
   helm repo update
   helm upgrade --install ofloki lucas/openfaas-loki \
       --namespace openfaas \
       --set lokiURL=http://loki.monitoring:3100 \
       --set logLevel=DEBUG
```

I tested that it is working as expected. Although, I think Github now supports OCI helm images ... so I might consider moving or mirroring it there as well.

**Comment by LucasRoesler** [comment]
I am now publishing to GHCR so the instructions are now just

```sh
helm upgrade --install ofloki oci:://ghcr.io/lucasroesler/charts/openfaas-loki \
       --namespace openfaas \
       --set lokiURL=http://loki.monitoring:3100 \
       --set logLevel=DEBUG
```
